### ISSUE TITLE
Gem name and release on rubygems

### ISSUE THREAD

**Issue by msalzburg** [jensljungblad/styleguide#9]
Since the name "styleguide" is already used/blocked on rubygems we should probably find a new name, rename the project/files and work towards an offical release on rubygems?

@jensljungblad do you have any names on your mind already?

**Comment by pedrocarmona** [comment]
given that rails 6.1 will probably have `ActionView::Component`, this project could be named: `actionguide`.

**Comment by IlanaB** [comment]
Is there a timeline for this? I'm interesting in including this in a project and prefer to include it as a rubygem

**Comment by jensljungblad** [comment]
> Is there a timeline for this? I'm interesting in including this in a project and prefer to include it as a rubygem

Interested to hear if you’re using this together with the accompanying components library or with something else?

**Comment by msalzburg** [comment]
> Is there a timeline for this? I'm interesting in including this in a project and prefer to include it as a rubygem

No timeline yet :(

**Comment by jensljungblad** [comment]
I also haven't checked in a while but there were several warnings being emitted by redcarpet and rouge which is a little annoying in a released gem.

As for a name, I was thinking about `elemental_components` for the components gem, seeing how elements are now the distinguishing feature when compared to `ActionView::Component`. Not sure if the styleguide should share the same name or if it should be considered something separate.

**Comment by jensljungblad** [comment]
Published to RubyGems finally: https://rubygems.org/gems/elemental_styleguide. Closing :)
